### ISSUE TITLE
demo跑起来好像堆栈益处了

### ISSUE THREAD

**Issue by daybreak1024** [acBool/RuntimeSourceCode#2]
![截屏2020-07-20 下午5 48 32](https://user-images.githubusercontent.com/15662933/87924300-468eb080-cab1-11ea-9bbe-69413ad3e8d4.png)
不知道怎么解决，还麻烦大神看看什么情况。

**Comment by daybreak1024** [comment]
补充：直接download下的code，然后run起来就出现这个问题了

**Comment by acBool** [comment]
fix
